<a href="https://colab.research.google.com/github/jiban03214/cpp-cod/blob/main/Final_Python_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Write a Python class Account with attributes like account number, date of opening balance and customer name, and methods like deposit, withdraw, and check balance and account history. The class is from the view of banking site. Different objects has to be created for different ac- count numbers.

In [ ]:
class Account:
    def __init__(self):
        self.account_number = int(input("Enter Account Number:: "))
        self.date_of_opening = str(input("Enter Date of Opening:: "))
        self.customer_name = str(input("Enter Customer Name:: "))
        self.balance = 0
        self.transaction_history = []

    def deposit(self, amount):
        if amount <= 0:
            print("Deposit amount must be greater than zero.")
        else:
            self.balance += amount
            self.transaction_history.append(f"Deposited: {amount}")

    def withdraw(self, amount):
        if amount <= 0:
            print("Withdrawal amount must be greater than zero.")
        else:
            if amount > self.balance:
                print("Insufficient balance for withdrawal.")
            else:
                self.balance -= amount
                self.transaction_history.append(f"Withdrew: {amount}")

    def check_balance(self):
        return(self.balance)

    def account_history(self):
        return(self.transaction_history)

if __name__ == "__main__":

    print("For Customer 1::____")
    print()
    account1 = Account()
    amount=float(input("Enter deposit amount:: "))
    account1.deposit(amount)
    amount=float(input("Enter withdraw amount:: "))
    account1.withdraw(amount)

    print("For Customer 2::____")
    print()
    account2 = Account()
    amount=float(input("Enter deposit amount:: "))
    account2.deposit(amount)
    amount=float(input("Enter withdraw amount:: "))
    account2.withdraw(amount)

    print("Account details of Customer1::____")
    print()
    print(f"Account1 Balance: ${account1.check_balance()}")
    print(f"Account1 Transaction History: {account1.account_history()}")

    print("Account details of Customer1::____")
    print()
    print(f"Account2 Balance: ${account2.check_balance()}")
    print(f"Account2 Transaction History: {account2.account_history()}")


For Customer 1::____

Enter Account Number:: 1002354
Enter Date of Opening:: 01-09-2022
Enter Customer Name:: jiban mandal
Enter deposit amount:: 50000
Enter withdraw amount:: 5000
For Customer 2::____

Enter Account Number:: 102356
Enter Date of Opening:: 05-09-2021
Enter Customer Name:: Raj roy
Enter deposit amount:: 45000
Enter withdraw amount:: 80000
Insufficient balance for withdrawal.
Account details of Customer1::____

Account1 Balance: $45000.0
Account1 Transaction History: ['Deposited: 50000.0', 'Withdrew: 5000.0']
Account details of Customer1::____

Account2 Balance: $45000.0
Account2 Transaction History: ['Deposited: 45000.0']



2. Write a python program that will generate a random integer list of length 24. Convert in into an numpy array. Reshape the array to a 6 x 4 matrix. Find transpose of the matrix.

In [ ]:
import numpy as np
import random

def generate_random_integer_list(length):
    return [random.randint(1, 100) for _ in range(length)]

if __name__ == "__main__":
    length = 24
    random_list = generate_random_integer_list(length)

    array_1d = np.array(random_list)

    array_2d = array_1d.reshape(6, 4)

    transpose_matrix = np.transpose(array_2d)

    print("Original 1D Array:")
    print(array_1d)

    print("\nReshaped 2D Matrix (6x4):")
    print(array_2d)

    print("\nTranspose of the Matrix:")
    print(transpose_matrix)

Original 1D Array:
[90 96  3 26 41 68 80 40 76 37 97 34 51 93 82 60 12 81 44 96 91 68 10  4]

Reshaped 2D Matrix (6x4):
[[90 96  3 26]
 [41 68 80 40]
 [76 37 97 34]
 [51 93 82 60]
 [12 81 44 96]
 [91 68 10  4]]

Transpose of the Matrix:
[[90 41 76 51 12 91]
 [96 68 37 93 81 68]
 [ 3 80 97 82 44 10]
 [26 40 34 60 96  4]]


3. From internet download csv file of iris data. Read the csv file into a python program. Create a numpy matrix called data that will contain the numeric attributes of iris data. Create a list named target that will contain the species column of iris dataset.

In [ ]:
import numpy as np
import csv

def read_iris_csv(file_path):
    data = []
    target = []

    with open(file_path, 'r') as file:
        csv_reader = csv.reader(file)
        header = next(csv_reader)

        for row in csv_reader:
            data.append([float(value) for value in row[:-1]])
            target.append(row[-1])

    return data, target

if __name__ == "__main__":
    file_path = "iris.csv"

    data, target = read_iris_csv(file_path)

    data = np.array(data)

    print("Numeric attributes matrix:")
    print(data)

    print("\nSpecies target list:")
    print(target)

Numeric attributes matrix:
[[1.00e+00 5.10e+00 3.50e+00 1.40e+00 2.00e-01]
 [2.00e+00 4.90e+00 3.00e+00 1.40e+00 2.00e-01]
 [3.00e+00 4.70e+00 3.20e+00 1.30e+00 2.00e-01]
 [4.00e+00 4.60e+00 3.10e+00 1.50e+00 2.00e-01]
 [5.00e+00 5.00e+00 3.60e+00 1.40e+00 2.00e-01]
 [6.00e+00 5.40e+00 3.90e+00 1.70e+00 4.00e-01]
 [7.00e+00 4.60e+00 3.40e+00 1.40e+00 3.00e-01]
 [8.00e+00 5.00e+00 3.40e+00 1.50e+00 2.00e-01]
 [9.00e+00 4.40e+00 2.90e+00 1.40e+00 2.00e-01]
 [1.00e+01 4.90e+00 3.10e+00 1.50e+00 1.00e-01]
 [1.10e+01 5.40e+00 3.70e+00 1.50e+00 2.00e-01]
 [1.20e+01 4.80e+00 3.40e+00 1.60e+00 2.00e-01]
 [1.30e+01 4.80e+00 3.00e+00 1.40e+00 1.00e-01]
 [1.40e+01 4.30e+00 3.00e+00 1.10e+00 1.00e-01]
 [1.50e+01 5.80e+00 4.00e+00 1.20e+00 2.00e-01]
 [1.60e+01 5.70e+00 4.40e+00 1.50e+00 4.00e-01]
 [1.70e+01 5.40e+00 3.90e+00 1.30e+00 4.00e-01]
 [1.80e+01 5.10e+00 3.50e+00 1.40e+00 3.00e-01]
 [1.90e+01 5.70e+00 3.80e+00 1.70e+00 3.00e-01]
 [2.00e+01 5.10e+00 3.80e+00 1.50e+00 3.00e-01]
 [2.10e+01 5.

4.Write a recursive function in python to find the factorial of a number. Using the function find the sum of 1/factorial(n) in the range of 0 to 10.



In [ ]:
def fact_recursive(n):
    if n == 0:
        return 1
    else:
        return n * fact_recursive(n - 1)

def calculate_sum():
    total_sum = 0
    for n in range(11):
        total_sum += 1 / fact_recursive(n)
    return total_sum

if __name__ == "__main__":
    num = int(input("Enter a number to find its factorial: "))

    factorial = fact_recursive(num)
    print(f"The factorial of {num} is: {factorial}")

    sum_of_inverse_factorials = calculate_sum()
    print("The sum of 1/factorial(n) in the range 0 to 10 is:", sum_of_inverse_factorials)


Enter a number to find its factorial: 5
The factorial of 5 is: 120
The sum of 1/factorial(n) in the range 0 to 10 is: 2.7182818011463845


5.Write a program that asks the user for a number and then prints out a list of all the divisors of that number.

In [ ]:
def prime(number):
    if number < 2:
        return False
    for i in range(2, int(number**0.5) + 1):
        if number % i == 0:
            return False
    return True

limit = int(input("Enter the number up to which you want to find prime numbers: "))

prime_numbers = [num for num in range(2, limit + 1) if prime(num)]

print("Prime numbers up to", limit, "are:", prime_numbers)

Enter the number up to which you want to find prime numbers: 8
Prime numbers up to 8 are: [2, 3, 5, 7]


6.Write a program to create a list of prime numbers upto a number given as user input. (Use a user defined function to check prime number).

In [ ]:
def find_div(number):
    divisors = []
    for i in range(1, number + 1):
        if number % i == 0:
            divisors.append(i)
    return divisors

number = int(input("Enter a number: "))
if number <= 0:
  print("Please enter a positive integer.")
else:
 divisors = find_div(number)
 print("Divisors of", number, "are:", divisors)

Enter a number: 9
Divisors of 9 are: [1, 3, 9]


7.Write a program to find factorial of a user provided number using recursive function.

In [ ]:
def factorial_recursive(n):
    if n == 0:
        return 1
    else:
        return n * factorial_recursive(n - 1)

if __name__ == "__main__":
    num = int(input("Enter a number to find its factorial: "))

    if num < 0:
        print("Factorial is not defined for negative numbers.")
    else:
        result = factorial_recursive(num)
        print(f"The factorial of {num} is: {result}")

Enter a number to find its factorial: 5
The factorial of 5 is: 120


8.Write a program in python to implement stack operation. Write your own function for push,pop and display.

In [ ]:
class Stack:
    def __init__(self):
        self.items = []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        if not self.is_empty():
            return self.items.pop()
        else:
            return None

    def is_empty(self):
        return len(self.items) == 0

    def display(self):
        if not self.is_empty():
            print("Stack contents:")
            for item in reversed(self.items):
                print(item)
        else:
            print("Stack is empty.")


stack = Stack()

while True:
        print("\nChoose an operation:")
        print("1. Push")
        print("2. Pop")
        print("3. Display")
        print("4. Exit")

        choice = int(input("Enter your choice : "))

        if choice == 1:
            item = input("Enter the item to push: ")
            stack.push(item)
            print(f"{item} has been pushed onto the stack.")

        elif choice == 2:
            item = stack.pop()
            if item is not None:
                print(f"{item} has been popped from the stack.")
            else:
                print("Stack is empty. Cannot pop.")

        elif choice == 3:
            stack.display()

        elif choice == 4:
            print("Exiting the program.")
            break

        else:
            print("Invalid choice. Please try again.")


Choose an operation:
1. Push
2. Pop
3. Display
4. Exit
Enter your choice : 1
Enter the item to push: 5
5 has been pushed onto the stack.

Choose an operation:
1. Push
2. Pop
3. Display
4. Exit
Enter your choice : 1
Enter the item to push: 9
9 has been pushed onto the stack.

Choose an operation:
1. Push
2. Pop
3. Display
4. Exit
Enter your choice : 1
Enter the item to push: 8
8 has been pushed onto the stack.

Choose an operation:
1. Push
2. Pop
3. Display
4. Exit
Enter your choice : 3
Stack contents:
8
9
5

Choose an operation:
1. Push
2. Pop
3. Display
4. Exit
Enter your choice : 2
8 has been popped from the stack.

Choose an operation:
1. Push
2. Pop
3. Display
4. Exit
Enter your choice : 3
Stack contents:
9
5

Choose an operation:
1. Push
2. Pop
3. Display
4. Exit
Enter your choice : 4
Exiting the program.


9. Write a program in python to implement quene operation. Write your own function for enqueue,dequenq and display.

In [ ]:
class Queue:
    def __init__(self):
        self.items = []

    def enqueue(self, item):
        self.items.append(item)

    def dequeue(self):
        if not self.is_empty():
            return self.items.pop(0)
        else:
            return None

    def is_empty(self):
        return len(self.items) == 0

    def display(self):
        if not self.is_empty():
            print("Queue contents:")
            for item in self.items:
                print(item)
        else:
            print("Queue is empty.")
queue = Queue()

while True:
        print("\nChoose an operation:")
        print("1. Enqueue")
        print("2. Dequeue")
        print("3. Display")
        print("4. Exit")

        choice = int(input("Enter your choice : "))

        if choice == 1:
            item = input("Enter the item to enqueue: ")
            queue.enqueue(item)
            print(f"{item} has been enqueued.")

        elif choice == 2:
            item = queue.dequeue()
            if item is not None:
                print(f"{item} has been dequeued.")
            else:
                print("Queue is empty. Cannot dequeue.")

        elif choice == 3:
            queue.display()

        elif choice == 4:
            print("Exiting the program.")
            break

        else:
            print("Invalid choice. Please try again.")


Choose an operation:
1. Enqueue
2. Dequeue
3. Display
4. Exit
Enter your choice : 1
Enter the item to enqueue: 5
5 has been enqueued.

Choose an operation:
1. Enqueue
2. Dequeue
3. Display
4. Exit
Enter your choice : 1
Enter the item to enqueue: 6
6 has been enqueued.

Choose an operation:
1. Enqueue
2. Dequeue
3. Display
4. Exit
Enter your choice : 9
Invalid choice. Please try again.

Choose an operation:
1. Enqueue
2. Dequeue
3. Display
4. Exit
Enter your choice : 3
Queue contents:
5
6

Choose an operation:
1. Enqueue
2. Dequeue
3. Display
4. Exit
Enter your choice : 2
5 has been dequeued.

Choose an operation:
1. Enqueue
2. Dequeue
3. Display
4. Exit
Enter your choice : 3
Queue contents:
6

Choose an operation:
1. Enqueue
2. Dequeue
3. Display
4. Exit
Enter your choice : 4
Exiting the program.
